"""empty message

Revision ID: 7b34801c7ede
Revises: None
Create Date: 2016-09-28 00:48:28.186804

"""

# revision identifiers, used by Alembic.
revision = '7b34801c7ede'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insider_trade',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('insider_name', sa.String(), nullable=False),
    sa.Column('insider_id', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('stock_name', sa.String(length=20), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('shares_traded', sa.Integer(), nullable=True),
    sa.Column('last_price', sa.Numeric(), nullable=True),
    sa.Column('shares_held', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_trade_insider_id'), 'insider_trade', ['insider_id'], unique=False)
    op.create_index(op.f('ix_insider_trade_last_date'), 'insider_trade', ['last_date'], unique=False)
    op.create_index(op.f('ix_insider_trade_stock_name'), 'insider_trade', ['stock_name'], unique=False)
    op.create_table('quote',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_name', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_name', 'date', name='quote--stock_name-date-unique')
    )
    op.create_index(op.f('ix_quote_date'), 'quote', ['date'], unique=False)
    op.create_index(op.f('ix_quote_stock_name'), 'quote', ['stock_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_stock_name'), table_name='quote')
    op.drop_index(op.f('ix_quote_date'), table_name='quote')
    op.drop_table('quote')
    op.drop_index(op.f('ix_insider_trade_stock_name'), table_name='insider_trade')
    op.drop_index(op.f('ix_insider_trade_last_date'), table_name='insider_trade')
    op.drop_index(op.f('ix_insider_trade_insider_id'), table_name='insider_trade')
    op.drop_table('insider_trade')
    ### end Alembic commands ###
